### PR TITLE
(Fixes #353) Nicer handling for reducing iterable workflow expressions and empty workflows

### LINKED ISSUE #353: Enable .reduceLeft(_ ~> _) on a list of pipeline activities
Currently it does not work, as it expect to return `PipleineActivit[_ <: ResourceObject]` instead of `WorkExpression`.

At the moment, one either need to use `.foldLeft[WorkflowExpression](WorkflowNoActivityExpression)(_ ~> _)` or `.map(x => x: WorkflowExpression).reduceLeft(_ ~> _)`. Neither looks elegant.

Be able to simply use `.reduceLeft(_ ~> _)` would be ideal.

### PR DESCRIPTION
**Pull request by sethyates**
Current handling of an `Iterable` of `WorkflowExpression` or `PipelineActivity` fails on `reduceLeft` given empty `Iterable`.  Also, handling of `foldLeft` with a start of `WorkflowNoActivityExpression` is cumbersome.  This change makes this common use case cleaner.

### CODE REVIEW

File: core/src/main/scala/com/krux/hyperion/workflow/WorkflowExpressionImplicits.scala [hunk 1]
```diff
@@ -7,15 +7,21 @@ import com.krux.hyperion.resource.ResourceObject
 
 trait WorkflowExpressionImplicits {
 
+  def emptyWorkflow: WorkflowExpression = WorkflowNoActivityExpression
```
Comment (realstraw) [inline core/src/main/scala/com/krux/hyperion/workflow/WorkflowExpressionImplicits.scala]: I'd put this under the companion `object WorkflowExpression`, like how Scala collections `List.emptyList`

Comment (sethyates) [inline core/src/main/scala/com/krux/hyperion/workflow/WorkflowExpressionImplicits.scala]: OK well I've gone with `WorkflowExpression.empty` to mirror `Seq.empty` as opposed to `WorkflowExpression.emptyWorkflowExpression`.
