### PR TITLE
(Fixes #381) Adding support for emr release label in S3DistCpActivity

### LINKED ISSUE #381: S3DistCpActivity fails when using emr-release label 4.X
In emr release label 4.X, the S3DistCpActivity fails. We need to use the `command-runner.jar` to run S3Distcp

### PR DESCRIPTION
**Pull request by arijitdey**
Here we check if the release label is set on the resources. If yes, we update the MapReduce to use the command-runner.jar along with s3-dist-cp command, or else use the default.

### CODE REVIEW

File: contrib/activity/definition/src/main/scala/com/krux/hyperion/activity/S3DistCpActivity.scala [hunk 1]
```diff
@@ -1,8 +1,8 @@
 package com.krux.hyperion.activity
 
-import com.krux.hyperion.adt.{ HBoolean, HInt, HString }
+import com.krux.hyperion.adt.{HBoolean, HInt, HString}
```
Comment (realstraw) [inline contrib/activity/definition/src/main/scala/com/krux/hyperion/activity/S3DistCpActivity.scala]: space after `{` is the preferred way

File: contrib/activity/definition/src/main/scala/com/krux/hyperion/activity/S3DistCpActivity.scala [hunk 2]
```diff
@@ -173,7 +173,17 @@ case class S3DistCpActivity[A <: EmrCluster] private (
     sourcePrefixesFile.map(s => Seq[HString]("--srcPrefixesFile", s))
   ).flatten.flatten
 
-  private def steps: Seq[MapReduceStep] = Seq(MapReduceStep("/home/hadoop/lib/emr-s3distcp-1.0.jar").withArguments(allArguments: _*))
+  private def steps: Seq[MapReduceStep] = {
+    if (runsOn.asManagedResource.get.releaseLabel.nonEmpty)
```
Comment (realstraw) [inline contrib/activity/definition/src/main/scala/com/krux/hyperion/activity/S3DistCpActivity.scala]: `runsOn.asManagedResource.flatMap(_.releaseLabel).nonEmpty`

File: contrib/activity/definition/src/main/scala/com/krux/hyperion/activity/S3DistCpActivity.scala [hunk 3]
```diff
@@ -173,7 +173,17 @@ case class S3DistCpActivity[A <: EmrCluster] private (
...
+      Seq(
+        MapReduceStep("command-runner.jar")
+          .withArguments(
+            (Seq[HString](HString(Left("s3-dist-cp"))) ++ allArguments): _*
```
Comment (realstraw) [inline contrib/activity/definition/src/main/scala/com/krux/hyperion/activity/S3DistCpActivity.scala]: why all these boilerplate? cannot you just use `("s3-dist-cp" +: allArguments)`?

File: contrib/activity/definition/src/main/scala/com/krux/hyperion/activity/S3DistCpActivity.scala [hunk 4]
```diff
@@ -173,7 +173,17 @@ case class S3DistCpActivity[A <: EmrCluster] private (
...
+          )
+    )
+    else
+      Seq(MapReduceStep("/home/hadoop/lib/emr-s3distcp-1.0.jar").withArguments(allArguments: _*))
```
Comment (realstraw) [inline contrib/activity/definition/src/main/scala/com/krux/hyperion/activity/S3DistCpActivity.scala]: Also I think you should put `Seq` outside, as it's repeated in the if/else

**Comment by realstraw** [comment]
👍
