### PR TITLE
(fixes #373, fixes #386) retry after throttling exception + refactor

### LINKED ISSUE #373: CLI and the aws client should retry with some delay on throttling exception
The following exception should only be thrown when it has been retried x times after certain delay

```
Exception in thread "main" com.amazonaws.AmazonServiceException: Rate exceeded (Service: DataPipeline; Status Code: 400; Error Code: ThrottlingException; Request ID: 0b7d248b-0744-11e6-b07d-1d3b6ceb95eb)
	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1275)
	at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:873)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:576)
	at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:362)
	at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:328)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:307)
	at com.amazonaws.services.datapipeline.DataPipelineClient.invoke(DataPipelineClient.java:1479)
	at com.amazonaws.services.datapipeline.DataPipelineClient.listPipelines(DataPipelineClient.java:857)
	at com.krux.hyperion.HyperionAwsClientForName.queryPipelines$1(HyperionAwsClient.scala:56)
```

### LINKED ISSUE #386: Inconsistent usage of JavaConvertions is used instead of JavaConverters
Some places JavaConversions is used instead of JavaConverters. In general JavaConverters should be preferred.

### PR DESCRIPTION
**Pull request by realstraw**

### CODE REVIEW

File: core/src/main/scala/com/krux/hyperion/HyperionAwsClient.scala [hunk 1]
```diff
@@ -1,18 +1,38 @@
...
 import com.krux.hyperion.DataPipelineDef._
 import org.slf4j.LoggerFactory
 
 sealed trait HyperionAwsClient {
+
+  val maxRetry = 3
+
   protected lazy val log = LoggerFactory.getLogger(getClass)
 
+  def throttleRetry[A](func: => A, n: Int = 0): A = {
```
Comment (sethyates) [inline core/src/main/scala/com/krux/hyperion/HyperionAwsClient.scala]: Can you add @tailrec. Does it make sense here?

**Comment by sethyates** [comment]
LGTM

File: core/src/main/scala/com/krux/hyperion/HyperionAwsClient.scala (hunk 1 above)
Comment (realstraw) [inline core/src/main/scala/com/krux/hyperion/HyperionAwsClient.scala]: I think should work, but I got "could not optimize @tailrec annotated method throttleRetry: it contains a recursive call not in tail position"
